name: Ubuntu_Server
on: 
  push:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: B4gol/deckflows/ssh@decent
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v3
    - run: source ubuntu-run.sh
    - name: Checkout
      timeout-minutes: 340
      uses: actions/checkout@v3.0.2


